---
title: "Stat 331 Project Report"
author: "Hailey Hossain, Zoey Miles, Ashley Navos, Vinithra Seshan"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
    code-fold: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
library(readr)
library(knitr)
library(gganimate)
library(broom)
library(kableExtra)
```

# Stat 331 Project Report

Hailey Hossain, Zoey Miles, Ashley Navos, Vinithra Seshan


##Introduction

Income and life expectancy have historically been shown to be correlated. At age 40, men in the top 1% income bracket are expected to live 14.6 years longer than those in the bottom 1%, and women can expect to live 10.1 years longer (Chetty et. al). We decided to explore the relationship between the income of the poorest 1% and life expectancy at birth to see how this correlation has changed throughout time and in different countries.

We hypothesize a positive relationship between Income Share of the Poorest 20% and Life Expectancy at Birth at the country level. As the share of total national income received by the bottom 20% increases, life expectancy is expected to rise. We expect this relationship as income inequality results in unequal access to public goods, such as basic necessities. This may influence stress and mental health, negatively affecting health. It has been determined that life expectancy increases continuously with income. Between the top 1% and bottom 1% of the income distribution, life expectancy differed by 15 years for men and 10 years for women (Chetty et. al). We expect the relationship to be moderate as there are many factors outside of income that influence life expectancy, such as access to healthcare, education, and personal choices. 

The two variables that we are using are the Income Share of the Poorest 20% and Life Expectancy at Birth. The Income Share of the Poorest 20% is from the World Bank Group and measures the proportion of a country's total income received by the bottom decile (20%). We have the proportions for each country and year, spanning 60 years. Life Expectancy at Birth is the average number of years a newborn child would live if current mortality patterns were to stay the same. The values were calculated using two main sources - the Human Mortality Database and the United Nations Population divisions World Population Prospects. We have estimates of Life Expectancy at Birth for each country and year, stretching over 200 years.
